apiVersion: apps/v1
kind: Deployment
metadata:
  name: formtable
  namespace: test
  labels:
    app: formtable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formtable
  template:
    metadata:
      labels:
        app: formtable
    spec:
      containers:
        - name: formtable
          image: artemiy111/formtable-nginx:latest
          # imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"