apiVersion: v1
kind: Service
metadata:
  name: formtable
  namespace: test
  labels:
    app: formtable
spec:
  type: NodePort
  selector:
    app: formtable
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080